project:
  type: website

website:
  title: "NetWeaver"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right: 
      - href: proposal.qmd
        text: Project Proposal
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

